name = Olender
description = A custom layout for Olender Mattress. It features a main content area with a single sidebar on the right.
template = olender-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[footer]         = Footer

; Styles
stylesheets[all][] = css/layouts/olender/olender.layout.css
stylesheets[all][] = css/layouts/olender/olender.layout.no-query.css